global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [ 'localhost:9090' ]

  - job_name: alloy
    metrics_path: /metrics
    static_configs:
      - targets: [ 'alloy:9080' ]

  - job_name: loki
    metrics_path: /metrics
    static_configs:
      - targets: [ 'loki:3100' ]

  - job_name: grafana
    metrics_path: /metrics
    static_configs:
      - targets: [ 'grafana:3000' ]

  - job_name: kafka
    static_configs:
      - targets: [ 'kafka-exporter:9308' ]

  - job_name: keycloak
    metrics_path: /metrics
    static_configs:
      - targets: [ 'keycloak:9000' ]

  - job_name: postgres
    static_configs:
      - targets: [ 'postgres-exporter:9187' ]

  - job_name: 'building-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [ 'building-service:8091' ]