spring:
  application.name: project-service
  datasource:
    url: jdbc:postgresql://localhost:5433/projects
    username: {$POSTGRES_USER:postgres}
    password: {$POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    user: {$POSTGRES_USER:postgres}
    password: {$POSTGRES_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
logging:
  level:
    liquibase: DEBUG
minio:
  bucket: projects
  access-key: {S3_ACCESS_KEY:project-service}
  secret-key: {S3_SECRET_KEY:project-service-secret}
  region: eu-central-1
  endpoint: http://localhost:9000