server:
  port: 8092

spring:
  application.name: project-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5433}/${POSTGRES_DB:projects}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    user: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: validate
logging:
  level:
    liquibase: DEBUG
minio:
  bucket: projects
  access-key: ${PROJECTS_ACCESS_KEY:project-service}
  secret-key: ${PROJECTS_SECRET_KEY:project-service-secret}
  region: eu-central-1
  url: http://${MINIO_HOST:localhost}:${MINIO_PORT:9000}